version: "3.2"
services:
  auth:
    command: node src/server.js
    build:
      context: auth
      dockerfile: Dockerfile
    container_name: auth
    ports:
      - published: ${APP_PORT:-3000}
        target: 3000
    environment:
      JWT_SECRET: ${JWT_SECRET}
    networks:
      movies:

  movies:
    command: node src/server.js
    build:
      context: movies
      dockerfile: Dockerfile
    container_name: movies
    ports:
      - published: ${MOVIES_PORT:-3001}
        target: ${MOVIES_PORT:-3001}
    environment:
      APP_PORT: ${MOVIES_PORT:-3001}
      JWT_SECRET: ${JWT_SECRET}
      OMDB_API_KEY: ${OMDB_API_KEY}
      LOGGER_LEVEL: ${LOGGER_LEVEL}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    networks:
      movies:

  db:
    image: mysql:8.0
    container_name: movies_db
    networks:
      movies:
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - movies-db:/var/lib/mysql


volumes:
  movies-db:

networks:
  movies:
    driver: bridge

