name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    services:
      mysql:
        image: mysql:8.0.32
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: movies
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        working-directory: ./movies
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: npm install, build, and test
        run: |
          #mysql
          sudo service mysql start
          mysql --host 127.0.0.1 --port 3306 -uroot -ppassword -e "SHOW DATABASES"
          mysql --host 127.0.0.1 --port 3306 -uroot -ppassword -e "CREATE DATABASE movies"
      - name: npm install and test
        working-directory: ./movies
        run: |
          cp ci.env .env
          npm install
          npm run db-migrate
          npm test
          
          
